on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'login to Docker hub '
        run: docker login --username ${{ secrets.HAMZA }} --password ${{ secrets.DOCKER_TOKEN }}

