on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing github action '
        run: pwd

       - name: 'testing github action '
         run: echo hamza

